# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.htmle
server:
  port: 8081
spring:
  cloud:
    stream:
      bindings:
        sample-in-0:
          destination: sample.messages
          group: sample
          binder: local_rabbit
        sample-out-0:
          destination: sample.messages
          group: sample
          binder: local_rabbit
      binders:
        local_rabbit:
          type: rabbit
          environment:
            spring:
              host: localhost
              port: 5672
              username: guest
              password: guest
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/sample?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: sample
    password: password
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
  #mvc:
  #  pathmatch:
  #    matching-strategy: ant_path_matcher
  messages:
    basename: "messages,config.i18n.messages"
    fallback-to-system-locale: false
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
# MyBatis Config
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: full
  mapper-locations: classpath*:mapper/*.xml
pagehelper:
  auto-dialect: true
  reasonable: true
  supportMethodsArguments: true