services:
  mysql:
    image: 'mysql:8.0'
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_USER=sample
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=sample
    command: --default-authentication-plugin=mysql_native_password
    labels:
      org.springframework.boot.service-connection: mysql
  kafka:
    image: rabbitmq:3.12
    ports:
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    labels:
      org.springframework.boot.service-connection: rabbitmq
  redis:
    image: redis:7.0
    ports:
      - 6379:6379
    labels:
      org.springframework.boot.service-connection: redis