version: '3.7'
services:
  mysql-server:
    image: mysql:8.0
    container_name: mysqlserver
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MODE=standalone
    networks:
      - default
volumes:
  mysql_data:
    driver: local