version: '3.7'
services:
  nacos-server:
    image: nacos/nacos-server:v2.3.2-slim
    container_name: nacosserver
    ports:
      - "8848:8848"
      - "9848:9848"
    volumes:
      - nacos_data:/home/nacos/logs
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
    networks:
      - default
volumes:
  nacos_data:
    driver: local